version: '3.7'

volumes:
 postgres_data:

services:
  postgres:
    image: postgres:13.6
    container_name: db_bgpu
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_DB: db_bgpu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data